name: CI

on:
    pull_request:
      branches: [main]
    push:
      branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn install --frozen-lockfile
    - run: yarn lint

    - name: Build & Bundlewatch
      uses: jackyef/bundlewatch-gh-action@master
      with:
        build-script: yarn build
        bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

    - name: Tests
      run: yarn test

    - name: Code Coverage
      uses: codecov/codecov-action@v1
      with:
        files: ./packages/core/coverage/lcov.info,./packages/utils/coverage/lcov.info,./packages/dom/coverage/lcov.info
        fail_ci_if_error: true
